export const DataTechnologies = [
  { id:1, name: "MONGO DB", tag: "mongodb" },
  { id:2, name: "EXPRESS JS", tag: "express" },
  { id:3, name: "ANGULAR", tag: "angularjs" },
  { id:4, name: "NODE JS", tag: "node" },
  { id:5, name: "BOOTSTRAP", tag: "bootstrap" },
  { id:6, name: "SPRING BOOT", tag: "spring-boot" },
  { id:7, name: "REACT", tag: "react" },
  { id:8, name: "SQL SERVER", tag: "sql-server" },
  { id:9, name: "AWS LAMBDA", tag: "aws-lambda" },
  { id:10, name: "AWS S3", tag: "aws-s3" },
  { id:11, name: "AWS RDS", tag: "aws-rds" },
  { id:12, name: "AWS EC2", tag: "aws-ec2" },
  { id:13, name: "LARAVEL", tag: "laravel" },
  { id:14, name: "C#", tag: "c-sharp" },
  { id:15, name: "DOCKER", tag: "docker" },
  { id:16, name: "GIT", tag: "git" },
  { id:17, name: "MOCKITO", tag: "mockito" },
  { id:18, name: "JEST JS", tag: "jest" },
  { id:19, name: "SPRING", tag: "spring" },
  { id:20, name: "POSTMAN", tag: "postman" },
  { id:21, name: "MYSQL", tag: "mysql" },
  { id:22, name: "LIT HTML", tag: "lit-html" },
  { id:23, name: "WORDPRESS", tag: "wordpress" },
  { id:24, name: "JQUERY", tag: "jquery" },
  { id:25, name: "ANDROID STUDIO", tag: "android-studio" },
  { id:26, name: "PHP", tag: "php" },
  { id:27, name: "SQL", tag: "sql" },
  { id:28, name: "JAVA", tag: "java" },
  { id:29, name: "JAVASCRIPT", tag: "javascript" },
  { id:30, name: "TYPESCRIPT", tag: "typescript" },
  { id:31, name: "ADOBE ILLUSTRATOR", tag: "illustrator" },
  { id:32, name: "ADOBE PHOTOSHOP", tag: "photoshop" },
  { id:33, name: "VISUAL STUDIO CODE", tag: "visual-studio-code" },
  { id:34, name: "VISUAL STUDIO", tag: "visual-studio" },
  { id:35, name: "API REST", tag: "rest" },
  { id:36, name: "API SOAP", tag: "soap" },
  { id:37, name: ".NET", tag: "dotnet" },
]

