export const DataTechnologies = [ //el ultimo es el 48
  { id:1, name: "MONGO DB", tag: "mongo-db", description: ["tec.mongodb1", "tec.mongodb2"] },
  { id:2, name: "EXPRESS JS", tag: "express", description: [""] },
  { id:3, name: "ANGULAR", tag: "angular", description: [""] },
  { id:4, name: "NODE JS", tag: "node", description: [""] },
  { id:5, name: "BOOTSTRAP", tag: "bootstrap", description: [""] },
  { id:6, name: "SPRING BOOT", tag: "spring-boot", description: [""] },
  { id:7, name: "REACT", tag: "react", description: [""] },
  { id:8, name: "SQL SERVER", tag: "sql-server", description: [""] },
  { id:9, name: "AWS LAMBDA", tag: "aws-lambda", description: [""] },
  { id:10, name: "AWS S3", tag: "aws-s3", description: [""] },
  { id:11, name: "AWS RDS", tag: "aws-rds", description: [""] },
  { id:12, name: "AWS EC2", tag: "aws-ec2", description: [""] },
  { id:13, name: "LARAVEL", tag: "laravel", description: [""] },
  { id:14, name: "C#", tag: "c-sharp", description: [""] },
  { id:15, name: "DOCKER", tag: "docker", description: [""] },
  { id:16, name: "GIT", tag: "git", description: [""] },
  { id:17, name: "MOCKITO", tag: "mockito", description: [""] },
  { id:18, name: "JEST JS", tag: "jest", description: [""] },
  { id:19, name: "SPRING", tag: "spring", description: [""] },
  { id:20, name: "POSTMAN", tag: "postman", description: [""] },
  { id:47, name: "FIGMA", tag: "figma", description: [""] },
  { id:48, name: "NEST JS", tag: "nestjs", description: [""] },
  { id:39, name: "SASS", tag: "sass", description: [""] },
  { id:40, name: ".NET CORE", tag: "core", description: [""] },
  { id:28, name: "VISUAL BASIC SCRIPT", tag: "vbscript", description: [""] },
  { id:27, name: "ASP.NET", tag: "asp", description: [""] },
  { id:21, name: "MYSQL", tag: "mysql", description: [""] },
  { id:22, name: "LIT HTML", tag: "lit-html", description: [""] },
  { id:23, name: "WORDPRESS", tag: "wordpress", description: [""] },
  { id:26, name: "PHP", tag: "php", description: [""] },
  { id:41, name: "TRELLO", tag: "trello", description: [""] },
  { id:42, name: "JIRA", tag: "jira", description: [""] },
  { id:43, name: "KANBAN", tag: "kanban", description: [""] },
  { id:45, name: "SCRUM", tag: "scrum", description: [""] },
  { id:46, name: "CSS", tag: "css", description: [""] },
  { id:44, name: "HTML", tag: "html", description: [""] },
  { id:24, name: "JQUERY", tag: "jquery", description: [""] },
  { id:29, name: "SQL", tag: "sql", description: [""] },
  { id:25, name: "ANDROID STUDIO", tag: "android-studio", description: [""] },
  { id:30, name: "JAVA", tag: "java", description: [""] },
  { id:37, name: "API REST", tag: "rest", description: [""] },
  { id:38, name: "API SOAP", tag: "soap", description: [""] },
  { id:33, name: "VISUAL STUDIO CODE", tag: "visual-studio-code", description: [""] },
  { id:34, name: "VISUAL STUDIO", tag: "visual-studio", description: [""] },
  { id:35, name: "JAVASCRIPT", tag: "javascript", description: [""] },
  { id:36, name: "TYPESCRIPT", tag: "typescript", description: [""] },
  { id:31, name: "ADOBE ILLUSTRATOR", tag: "illustrator", description: [""] },
  { id:32, name: "ADOBE PHOTOSHOP", tag: "photoshop", description: [""] },
]

