export const InfoExperience = [
  {
    id: "nttdata",
    title: "NTT DATA Europe & LATAM",
    position: "Desarrollador Full Stack",
    date: "Julio 2021 - presente",
    description: ["NTT DATA, parte de NTT Group, es uno de los 10 principales proveedores de servicios de TI a nivel mundial","Ofrecen servicios de consultoría, soluciones industriales, servicios de procesos de negocio, modernización de TI y servicios gestionados."],
    tasks: [
      "Desarrollo de microservicios haciendo uso de Java Spring Boot",
      "Gestión de contenedores haciendo uso de Docker",
      "Creación y mantenimiento de diversos componentes para el front-end haciendo uso de Angular13",
      "Creación microservicios haciendo uso de node js con funciones lambda - AWS",
      "Gestión de bases de datos MySQL con el servicio RDS - AWS",
      "Agregando módulos para el front-end haciendo uso de Lit-Html (JS)",
      "Recreación del front-end del sistema silverlight haciendo uso de Angular 11",
      "Test de módulos haciendo uso de jest.js",
      "Consumo de API REST",
    ],
    ownLogo: true,
    sub: true,
    sections: ["renfe","datadis","ree","ibost"],
  },
  {
    id: "renfe",
    title: "RENFE",
    position: "Desarrollador Full Stack",
    date: "Noviembre 2022 - presente",
    description: ["Plataforma de administración de las vías ferroviarias y trenes de España, incluyendo rutas, cargas, estaciones, etc","Tecnologías usadas: Java Spring - Angular13"],
    tasks: [
      "Desarrollo deL backend haciendo uso de Java Spring",
      "Creación, mantenimiento y mejora de diversos componentes para el front-end haciendo uso de Angular13",
    ],
    ownLogo: true,
    sub: false,
    images: 9,
  },
  {
    id: "datadis",
    title: "DATADIS",
    position: "Desarrollador Full Stack",
    date: "Febrero 2022 - Octubre 2022",
    description: ["Es una plataforma de datos de consumo eléctrico que permite al administrador ver, agregar, editar y eliminar diversas empresas y sus consumos eléctricos a una base de datos mediante una API y a los usuarios en general verificar el consumo eléctrico en diversos periodos de tiempo","Tecnologías usadas: Java Spring Boot - Docker - Angular13"],
    tasks: [
      "Desarrollo de microservicios haciendo uso de Java Spring Boot",
      "Gestión de contenedores haciendo uso de Docker",
      "Creación, mantenimiento y mejora de diversos componentes para el front-end haciendo uso de Angular13",
    ],
    ownLogo: true,
    sub: false,
    images: 7,
  },
  {
    id: "ree",
    title: "RED ELECTRICA DE ESPAÑA",
    position: "Desarrollador Full Stack",
    date: "Diciembre 2021 - Enero 2022",
    description: ["Sistema administrativo y dashboard para la red eléctrica de España","El sistema permite a la población en general verificar su consumo eléctrico mediante diversos gráficos","Tecnologías usadas: Java Spring Boot - Docker - Angular13"],
    tasks: [
      "Creación microservicios haciendo uso de node js con funciones lambda - AWS",
      "Gestión de bases de datos MySQL con el servicio RDS - AWS",
      "Agregando módulos para el front-end haciendo uso de Lit-Html (JS)",
    ],
    ownLogo: true,
    sub: false,
    images: 9,
  },
  {
    id: "ibost",
    title: "IBOST",
    position: "Desarrollador Front-End",
    date: "Julio 2021 - Noviembre 2021",
    description: ["El proyecto consistía en la migración de un sistema basado en Silverlight a un nuevo proyecto usando la tecnología Angular11","iBost es una empresa que se dedica a la distribución de diversas resistencias eléctricas y su sistema requería una administración de pedidos y clientes","Tecnologías usadas: jest.js - API REST - Angular11"],
    tasks: [
      "Recreación del front-end del sistema silverlight haciendo uso de Angular 11",
      "Test de módulos haciendo uso de jest.js",
      "Consumo de API REST",
    ],
    ownLogo: true,
    sub: false,
    images: 6,
  },
]

