export const InfoExperience = [
  {
    id: "nttdata",
    title: "NTT DATA Europe & LATAM",
    position: "info-exp.full",
    date: "nttdata.date",
    description: ["nttdata.desc1","nttdata.desc2"],
    tasks: ["nttdata.task1","nttdata.task2","nttdata.task3","nttdata.task4","nttdata.task5","nttdata.task6","nttdata.task7","nttdata.task8","nttdata.task9","nttdata.task10","nttdata.task11"],
    ownLogo: true,
    sub: true,
    sections: ["renfe","datadis","ree","ibost"],
  },
  {
    id: "renfe",
    title: "RENFE",
    position: "info-exp.full",
    date: "renfe.date",
    description: ["renfe.desc1","renfe.desc2"],
    tasks: ["renfe.task1","renfe.task2"],
    ownLogo: true,
    sub: false,
    images: 9,
  },
  {
    id: "datadis",
    title: "DATADIS",
    position: "info-exp.full",
    date: "datadis.date",
    description: ["datadis.desc1","datadis.desc2"],
    tasks: ["datadis.task1","datadis.task2","datadis.task3"],
    ownLogo: true,
    sub: false,
    images: 7,
  },
  {
    id: "ree",
    title: "RED ELECTRICA DE ESPAÑA",
    position: "info-exp.full",
    date: "ree.date",
    description: ["ree.desc1","ree.desc2","ree.desc3"],
    tasks: ["ree.task1","ree.task2","ree.task3"],
    ownLogo: true,
    sub: false,
    images: 9,
  },
  {
    id: "ibost",
    title: "IBOST",
    position: "info-exp.front",
    date: "ibost.date",
    description: ["ibost.desc1","ibost.desc2","ibost.desc3"],
    tasks: ["ibost.task1","ibost.task2","ibost.task3"],
    ownLogo: true,
    sub: false,
    images: 6,
  },
  {
    id: "adiasoft",
    title: "ADIASOFT E.I.R.L",
    position: "info-exp.full",
    date: "adiasoft.date",
    description: ["adiasoft.desc1","adiasoft.desc2","adiasoft.desc3"],
    tasks: ["adiasoft.task1","adiasoft.task2","adiasoft.task3"],
    ownLogo: true,
    sub: false,
    images: 3,
  },
]

